# Generated by Django 5.0.2 on 2024-02-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlyWheelMedicalApp', '0002_remove_manager_userid_remove_client_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdirection',
            name='DoctorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FlyWheelMedicalApp.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Qualification',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.CharField(max_length=150),
        ),
    ]
