# Generated by Django 5.0.2 on 2024-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlyWheelMedicalApp', '0003_analysisdirection_doctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.TextField(),
        ),
    ]
