# Generated by Django 5.0.2 on 2024-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlyWheelMedicalApp', '0004_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ServiceName',
            field=models.CharField(max_length=255),
        ),
    ]
